### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "password": "password123",
  "email": "john@example.com"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "password1234"
}

### Get Profile (session required)
GET http://localhost:3000/auth/profile

### Reset Password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "username": "john@example.com",
  "newPassword": "newpassword123"
}

### Logout
POST http://localhost:3000/auth/logout